/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Arithmetics */

#ifndef _Included_Arithmetics
#define _Included_Arithmetics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Arithmetics
 * Method:    addValues
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Arithmetics_addValues
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Arithmetics
 * Method:    substractValues
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Arithmetics_substractValues
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Arithmetics
 * Method:    multiplyValues
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Arithmetics_multiplyValues
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Arithmetics
 * Method:    divideValues
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Arithmetics_divideValues
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Arithmetics
 * Method:    complimentValue
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_Arithmetics_complimentValue
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
